development:
  adapter: mysql2
  encoding: utf8
  database: cloud_edit_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  database: cloud_edit_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  database: cloud_edit
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
